[package]
name = "sshfs"
authors = ["SSHFS Maintainers"]
version = "0.1.0"
publish = false
edition = "2021"

[lib]
name = "libsshfs"
crate-type = ["staticlib", "rlib"]

[dependencies]
c2rust-bitfields= "0.3"
libc= "0.2"
