[package]
name = "sshfs"
authors = ["SSHFS Maintainers"]
version = "0.1.0"
publish = false
edition = "2021"

[lib]
name = "libsshfs"
crate-type = ["staticlib", "rlib"]

[dependencies]
libc= "0.2"
libfuse-sys = {version = "0.4.0", features = ["fuse_35"] }
